name: Build an image
on:
  workflow_call:
    inputs:
      version:
        description: "image version"
        required: true
        type: string
    secrets:
      username:
        description: "registry username"
        required: true
      password:
        description: "registry password"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push versioned image only
        if: github.ref  != 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          repository: vaagn/test-docker-images
          tags: ${{ inputs.version }}

      - name: Build and push versioned and latest image
        if: github.ref  == 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.username }}
          tag_with_ref: true
          password: ${{ secrets.password }}
          repository: vaagn/test-docker-images
          tags: ${{ inputs.version }}